CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE PERFIL(
	CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	PRIMARY KEY(CODIGO)
)ENGINE=INNODB;

CREATE TABLE CURSO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	DT_INICIO DATETIME NOT NULL,
	DT_TERMINO DATETIME NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE USUARIO(
	NUMERO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	DATA DATETIME NOT NULL,
	NOME VARCHAR(80) NOT NULL,
    PERFIL_CODIGO INT UNSIGNED NOT NULL,
    CURSO_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY(NUMERO),
	FOREIGN KEY(PERFIL_CODIGO) REFERENCES PERFIL(CODIGO),
	FOREIGN KEY(CURSO_ID) REFERENCES CURSO(ID)
)ENGINE=INNODB;

CREATE TABLE CLASSIFICACAO(
	CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    PRIMARY KEY(CODIGO)
)ENGINE=INNODB;

CREATE TABLE LINGUA(
	CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME CHAR(2) NOT NULL,
    PRIMARY KEY(CODIGO)
)ENGINE=INNODB;

CREATE TABLE AUTOR(
	CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    PRIMARY KEY(CODIGO)
)ENGINE=INNODB;

CREATE TABLE MIDIA(
	CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    PRIMARY KEY(CODIGO)
)ENGINE=INNODB;

CREATE TABLE EDITORA(
	CNPJ CHAR(20) NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    PRIMARY KEY(CNPJ)
)ENGINE=INNODB;

CREATE TABLE OBRAS(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    PAGINAS INT UNSIGNED NOT NULL,
    CLASSIFICACAO_CODIGO INT UNSIGNED NOT NULL,
    LINGUA_CODIGO INT UNSIGNED NOT NULL,
    AUTOR_CODIGO INT UNSIGNED NOT NULL,
    MIDIA_CODIGO INT UNSIGNED NOT NULL,
    EDITORA_CNPJ CHAR(20) NOT NULL,
    PRIMARY KEY(ID),
	FOREIGN KEY(CLASSIFICACAO_CODIGO) REFERENCES CLASSIFICACAO(CODIGO),
	FOREIGN KEY(LINGUA_CODIGO) REFERENCES LINGUA(CODIGO),
	FOREIGN KEY(AUTOR_CODIGO) REFERENCES AUTOR(CODIGO),
	FOREIGN KEY(MIDIA_CODIGO) REFERENCES MIDIA(CODIGO),
	FOREIGN KEY(EDITORA_CNPJ) REFERENCES EDITORA(CNPJ)
)ENGINE=INNODB;

CREATE TABLE EMPRESTIMO(
	NUMERO INT UNSIGNED AUTO_INCREMENT NOT NULL,
    VALOR DOUBLE(8,2) NOT NULL,
    DATA DATETIME NOT NULL,
    DEVOLUCAO DATETIME NOT NULL,
    OBRAS_ID INT UNSIGNED NOT NULL,
    USUARIO_NUMERO INT UNSIGNED NOT NULL,
    PRIMARY KEY(NUMERO),
	FOREIGN KEY(OBRAS_ID) REFERENCES OBRAS(ID),
	FOREIGN KEY(USUARIO_NUMERO) REFERENCES USUARIO(NUMERO)
)ENGINE=INNODB;

