CREATE DATABASE ELEICAO;
USE ELEICAO;

CREATE TABLE LOCALIDADE(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	REGIAO VARCHAR(150) NOT NULL,
	PRIMARY KEY(ID)
)ENGINE=INNODB; 

CREATE TABLE ZONAS(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	ENDERECO VARCHAR(140) NOT NULL,
	LOCALIDADES_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(LOCALIDADES_ID) REFERENCES LOCALIDADES(ID)
)ENGINE=INNODB;

CREATE TABLE SECOES(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	DESCRICAO VARCHAR(140) NOT NULL,
	ZONAS_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ZONAS_ID) REFERENCES ZONAS(ID)
)ENGINE=INNODB;

CREATE TABLE ELEITOR(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	ENDERECO VARCHAR(140) NOT NULL,
	SECOES_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(SECOES_ID) REFERENCES SECOES(ID)
)ENGINE=INNODB;

CREATE TABLE VOTO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	DATA_ DATETIME AUTO_INCREMENT NOT NULL,
	ENDERECO VARCHAR(140) NOT NULL,
	ELEITOR_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ELEITOR_ID) REFERENCES ELEITOR(ID)
)ENGINE=INNODB;

CREATE TABLE CARGO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	DESCRICAO VARCHAR(140) NOT NULL,
	VOTO_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(VOTO_ID) REFERENCES VOTO(ID)
)ENGINE=INNODB;

CREATE TABLE CANDIDATO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	ENDERECO VARCHAR(150) NOT NULL,
	CARGO_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(CARGO_ID) REFERENCES CARGO(ID)
)ENGINE=INNODB;

CREATE TABLE PARTIDO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	SIGLA VARCHAR(10) NOT NULL,
	CANDIDATO_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(CANDIATO_ID) REFERENCES CANDIDATO(ID)
)ENGINE=INNODB;
