CREATE DATABASE ESTOQUE;
USE ESTOQUE;

CREATE TABLE FORNECEDOR(
	CNPJ CHAR(20) NOT NULL,
    NOME VARCHAR(80) NOT NULL,
	ENDERECO VARCHAR(140) NOT NULL,
    PRIMARY KEY(CNPJ)
)ENGINE=INNODB;

CREATE TABLE COMPRAS(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    DATE DATETIME NOT NULL,
    VALOR DOUBLE(9,2) NOT NULL,
    FORNECEDOR_CNPJ CHAR(20) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ)
)ENGINE=INNODB;

CREATE TABLE CLIENTES(
	CPF CHAR(14) NOT NULL,
    NOME VARCHAR(80) NOT NULL,
	ENDERECO VARCHAR(140) NOT NULL
)ENGINE=INNODB;

CREATE TABLE VENDAS(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    DATE DATETIME NOT NULL,
    VALOR DOUBLE(9,2) NOT NULL,
    CLIENTES_CPF CHAR(14) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CLIENTES_CPF) REFERENCES CLIENTES(CPF)
)ENGINE=INNODB;

CREATE TABLE NOTA_FISCAL(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    DATA DATETIME NOT NULL,
    VALOR DOUBLE(9,2) NOT NULL,
    TIPO CHAR(1) NOT NULL,
    COMPRAS_ID INT UNSIGNED NOT NULL,
    VENDAS_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(COMPRAS_ID) REFERENCES COMPRAS(ID),
    FOREIGN KEY(VENDAS_ID) REFERENCES VENDAS(ID)
)ENGINE=INNODB;

CREATE TABLE ALMOXARIFADO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    ENDERECO VARCHAR(140) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE PRODUTOS(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    PRECO DOUBLE(9,2) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE ESTOQUE(
	ALMOXARIFADO_ID INT UNSIGNED NOT NULL,
    PRODUTOS_ID INT UNSIGNED NOT NULL,
    DATE DATETIME NOT NULL,
    QUANTIDADE INT UNSIGNED NOT NULL,
    PRIMARY KEY(ALMOXARIFADO_ID),
    PRIMARY KEY(PRODUTOS_ID),
    FOREIGN KEY(ALMOXARIFADO_ID) REFERENCES ALMOXARIFADO(ID),
    FOREIGN KEY(PRODUTOS_ID) REFERENCES PRODUTOS(ID)
)ENGINE=INNODB;
