CREATE DATABASE HOTEL_28;

USE HOTEL_28;

CREATE TABLE CLIENTE(
	ID INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    CPF INT NOT NULL,
    TIPO_CONVENIO VARCHAR(40) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE RESERVA(
	ID INT AUTO_INCREMENT NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    QUARTO INT NOT NULL,
    VALOR DOUBLE(9,2) NOT NULL,
    CLIENTE_ID INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(ID)
)ENGINE=INNODB;

CREATE TABLE HOSPEDE(
	ID INT AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(80) NOT NULL,
    TELEFONE CHAR(15) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    RESERVA_ID INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(RESERVA_ID) REFERENCES RESERVA(ID)
)ENGINE=INNODB;

CREATE TABLE QUARTO(
	ID INT AUTO_INCREMENT NOT NULL,
	NUMERO INT NOT NULL,
    ANDAR INT NOT NULL,
    CLASSIFICACAO VARCHAR(40) NOT NULL,
    HOSPEDE_ID INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(HOSPEDE_ID) REFERENCES HOSPEDE(ID)
)ENGINE=INNODB;

CREATE TABLE SERVICO_COPA(
	ID INT AUTO_INCREMENT NOT NULL,
    REGISTRO VARCHAR(100),
    TIPO_SERVICO VARCHAR(40),
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE SERVICOS(
	ID INT AUTO_INCREMENT NOT NULL,
	ITENS VARCHAR(50) NOT NULL,
	TIPO VARCHAR(50) NOT NULL,
    OBSERVACAO VARCHAR(100) NOT NULL,
	QUARTO_ID INT NOT NULL,
    SERVICO_COPA_ID INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(QUARTO_ID) REFERENCES QUARTO(ID),
    FOREIGN KEY(SERVICO_COPA_ID) REFERENCES SERVICO_COPA(ID)
)ENGINE=INNODB;

INSERT INTO CLIENTE(ID, NOME, CPF, TIPO_CONVENIO)
VALUES(NULL, "BRASILEIRO", 123, "SAMBA E FUTEBOL");
INSERT INTO CLIENTE(ID, NOME, CPF, TIPO_CONVENIO)
VALUES(NULL, "BOLIVIANO", 321, "INDIO E ALTITUDE");
INSERT INTO CLIENTE(ID, NOME, CPF, TIPO_CONVENIO)
VALUES(NULL, "MEXICANO", 335, "SOMBREIRO E PIMENTA");

INSERT INTO RESERVA(ID, DATA_INICIO, DATA_FIM, QUARTO, VALOR, CLIENTE_ID)
VALUES(NULL, 09/07/1822, 09/07/2022, 21, 1390.99, 1);
INSERT INTO RESERVA(ID, DATA_INICIO, DATA_FIM, QUARTO, VALOR, CLIENTE_ID)
VALUES(NULL, 08/06/1825, 08/06/2025, 41, 90.99, 2);
INSERT INTO RESERVA(ID, DATA_INICIO, DATA_FIM, QUARTO, VALOR, CLIENTE_ID)
VALUES(NULL, 09/27/1821, 09/27/2021, 55, 390.99, 3);

INSERT INTO HOSPEDE(ID, NOME, TELEFONE, EMAIL, RESERVA_ID)
VALUES(NULL, "PARAGUAIO", "123456789012345", "PARAGUAI@MUAMBA.COM", 1);
INSERT INTO HOSPEDE(ID, NOME, TELEFONE, EMAIL, RESERVA_ID)
VALUES(NULL, "CHILENO", "12345678954321", "CHILENO@MONTANHA.COM", 2);
INSERT INTO HOSPEDE(ID, NOME, TELEFONE, EMAIL, RESERVA_ID)
VALUES(NULL, "GUATEMALTECO", "21436578954321", "GUATEMALTECO@BANANA.COM", 3);

INSERT INTO QUARTO(ID, NUMERO, ANDAR, CLASSIFICACAO, HOSPEDE_ID)
VALUES(NULL, 120, 1, "MUITO RUIM", 1);
INSERT INTO QUARTO(ID, NUMERO, ANDAR, CLASSIFICACAO, HOSPEDE_ID)
VALUES(NULL, 510, 5, "BEM MAIS OU MENOS", 3);

INSERT INTO SERVICO_COPA(ID, REGISTRO, TIPO_SERVICO)
VALUES(NULL, "BLA BLA BLA", "TELEVISIONAR JOGO");
INSERT INTO SERVICO_COPA(ID, REGISTRO, TIPO_SERVICO)
VALUES(NULL, "ALB ALB ALB", "VENDAS DE TACO");

INSERT INTO SERVICOS(ID, ITENS, TIPO, OBSERVACAO, QUARTO_ID, SERVICO_COPA_ID)
VALUES(NULL, "TACO", "VENDA DE PRODUTO", "MUITA PIMENTA", 1, 2);
INSERT INTO SERVICOS(ID, ITENS, TIPO, OBSERVACAO, QUARTO_ID, SERVICO_COPA_ID)
VALUES(NULL, "TACO", "VENDA DE PRODUTO", "MUITA CACHAÇA", 2, 2);
INSERT INTO SERVICOS(ID, ITENS, TIPO, OBSERVACAO, QUARTO_ID, SERVICO_COPA_ID)
VALUES(NULL, "TELEVISAO", "ASSISTIR", "MUITO FUTEBOL", 1, 1);
INSERT INTO SERVICOS(ID, ITENS, TIPO, OBSERVACAO, QUARTO_ID, SERVICO_COPA_ID)
VALUES(NULL, "TELEVISAO", "ASSISTIR", "MUITA NOVELA", 2, 1);

-- 9) Apagar todos as reservas com valor maior que 100,00; Delete from reservas where valor &gt; 100;
DELETE FROM RESERVA WHERE VALOR > 100;

-- 10) Apagar todos hospedes
DELETE FROM HOSPEDE WHERE ID >= 0;

-- 11) Atualizar o valor das reservas para 100,00 onde a data for igual a data de hoje.
UPDATE RESERVA SET VALOR = 100 WHERE DATA_INICIO = 08/18/2020;

-- 12) Selecionar todas reservas feitas entre maio e junho de 2018
SELECT * FROM RESERVA WHERE DATA_INICIO BETWEEN 05/01/2018 AND 06/01/2018;

-- 13) Quantos clientes existem?
SELECT COUNT(*) AS CLIENTES_EXISTENTES FROM CLIENTE;
