CREATE DATABASE LOJA_2C1;

USE LOJA_2C1;

CREATE TABLE EMPRESA(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL,
    ENDERECO VARCHAR(45) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE CLIENTES(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    ENDERECO VARCHAR(45) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CIDADE VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE LOJAS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(80) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(60) NOT NULL,
    EMPRESA_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(EMPRESA_ID) REFERENCES EMPRESA(ID)
)ENGINE=INNODB;

CREATE TABLE EMPREGADOS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    ENDERECO VARCHAR(45) NOT NULL,
    TELEFONE VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    LOJAS_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(LOJAS_ID) REFERENCES LOJAS(ID)
)ENGINE=INNODB;

CREATE TABLE PRODUTOS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VALOR DOUBLE(9,2) UNSIGNED NOT NULL,
    QUANTIDADE INT UNSIGNED NOT NULL,
    DESCRICAO VARCHAR(100),
	OBSERVACAO VARCHAR(100),
    LOJAS_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(LOJAS_ID) REFERENCES LOJAS(ID)
)ENGINE=INNODB;

CREATE TABLE VENDAS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DATA DATE NOT NULL,
	TOTAL DOUBLE(9,2) NOT NULL,
    HORA TIME NOT NULL,
    OBSERVACAO VARCHAR(60),
    LOJAS_ID INT UNSIGNED NOT NULL,
	CLIENTES_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(LOJAS_ID) REFERENCES LOJAS(ID),
    FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID)
)ENGINE=INNODB;

CREATE TABLE ITENS_VENDA(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    VALOR_UNITARIO DOUBLE(9,2) UNSIGNED NOT NULL,
    QUANTIDADE INT UNSIGNED NOT NULL,
    VENDAS_ID INT UNSIGNED NOT NULL,
    PRODUTOS_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(VENDAS_ID) REFERENCES VENDAS(ID),
    FOREIGN KEY(PRODUTOS_ID) REFERENCES PRODUTOS(ID)
)ENGINE=INNODB;

USE LOJA_2C1;

INSERT INTO EMPRESA(ID, NOME, ENDERECO, TELEFONE, EMAIL) VALUES (NULL, 'CHAVES SA', 'RUA TELEVISA, NUMERO 8', '987654321', 'CHAVES@GMAIL.COM');
INSERT INTO EMPRESA(ID, NOME, ENDERECO, TELEFONE, EMAIL) VALUES (NULL, 'QUICO LTDA', 'RUA TELEVISA, NUMERO 18', '123456789', 'QUICO@GMAIL.COM');
INSERT INTO EMPRESA(ID, NOME, ENDERECO, TELEFONE, EMAIL) VALUES (NULL, 'SEU MADRUGA LTDA', 'RUA TELEVISA, NUMERO 65', '34343434', 'MADRUGUINHA@GMAIL.COM');

INSERT INTO LOJAS(ID, NOME, ENDERECO, CIDADE, TIPO, EMPRESA_ID) VALUES (NULL, 'REFRESCOS DO CHAVES', 'RUA TANGAMANDAPIO NUMERO 37', 'CIDADE DO MEXICO', 'COMERCIO', 4);
INSERT INTO LOJAS(ID, NOME, ENDERECO, CIDADE, TIPO, EMPRESA_ID) VALUES (NULL, 'SUPER DE QUICO', 'RUA TANGAMANDAPIO NUMERO 39', 'CIDADE DO MEXICO', 'COMERCIO', 5);
INSERT INTO LOJAS(ID, NOME, ENDERECO, CIDADE, TIPO, EMPRESA_ID) VALUES (NULL, 'MERCEARIA DO MADRUGUINHA', 'RUA DO BARRIL 75', 'ACAPULCO', 'SUPERMERCADO', 6);

INSERT INTO EMPREGADOS(ID, NOME, ENDERECO, TELEFONE, CIDADE, EMAIL, ESTADO, LOJAS_ID) VALUES (NULL, 'SEU BARRIGA', 'RUA CACHALOTE VILA DOS ELEFANTES', '777777777',  'CIDADE DO MEXICO', 'SEUBARRIGA@GMAIL.COM', 'SP', 2);
INSERT INTO EMPREGADOS(ID, NOME, ENDERECO, TELEFONE, CIDADE, EMAIL, ESTADO, LOJAS_ID) VALUES (NULL, 'DONA FLORINDA', 'RUA GIRAFA 175', '888888888',  'CIDADE DO MEXICO', 'FLORINDA@GMAIL.COM', 'RJ', 3);
INSERT INTO EMPREGADOS(ID, NOME, ENDERECO, TELEFONE, CIDADE, EMAIL, ESTADO, LOJAS_ID) VALUES (NULL, 'CHIQUINHA', 'RUA DO BARRIL 124', '666666666',  'CIDADE DO MEXICO', 'CHILINDRINA@GMAIL.COM', 'SP', 4);

INSERT INTO CLIENTES(ID, NOME, ENDERECO, TELEFONE, CIDADE, EMAIL, ESTADO) VALUES (NULL, 'JAIMINHO', 'RUA TANGAMANDAPIO NUMERO 780', '555555555', 'PIRACICABA', 'JAIMINHO@GMAIL.COM', 'SP');
INSERT INTO CLIENTES(ID, NOME, ENDERECO, TELEFONE, CIDADE, EMAIL, ESTADO) VALUES (NULL, 'DONA NEVES', 'RUA DAS LOUCAS 129', '35353535', 'PRESIDENTE PRUDENTE', 'DONANEVES@GMAIL.COM', 'SP');
INSERT INTO CLIENTES(ID, NOME, ENDERECO, TELEFONE, CIDADE, EMAIL, ESTADO) VALUES (NULL, 'GIRAFALES', 'RUA DOS MESTRES 164', '36563451', 'CIDADE DO MEXICO', 'GIRAFALES@GMAIL.COM', 'MG');

INSERT INTO PRODUTOS(ID, VALOR, QUANTIDADE, DESCRICAO, OBSERVACAO, LOJAS_ID) VALUES (NULL, 5.99, 5, 'SUCO DE TAMARINDO', 'PARECE DE GROSELHA E TEM GOSTO DE LIMAO', 2);
INSERT INTO PRODUTOS(ID, VALOR, QUANTIDADE, DESCRICAO, OBSERVACAO, LOJAS_ID) VALUES (NULL, 10.99, 1, 'SUCO DE UVA', '', 3);
INSERT INTO PRODUTOS(ID, VALOR, QUANTIDADE, DESCRICAO, OBSERVACAO, LOJAS_ID) VALUES (NULL, 15.99, 15, 'CHURROS', 'DE TODOS OS TIPOS', 4);

INSERT INTO VENDAS(ID, DATA, TOTAL, HORA, OBSERVACAO, LOJAS_ID, CLIENTES_ID) VALUES(NULL, 06/20/2020, 2, '20:47', '', 2, 1);
INSERT INTO VENDAS(ID, DATA, TOTAL, HORA, OBSERVACAO, LOJAS_ID, CLIENTES_ID) VALUES(NULL, 05/18/2020, 6, '15:13', '', 3, 2);
INSERT INTO VENDAS(ID, DATA, TOTAL, HORA, OBSERVACAO, LOJAS_ID, CLIENTES_ID) VALUES(NULL, 04/19/2020, 5, '12:54', '', 4, 3);

INSERT INTO ITENS_VENDA(ID, VALOR_UNITARIO, QUANTIDADE, VENDAS_ID, PRODUTOS_ID) VALUES(NULL, 10, 3, 2, 1);
INSERT INTO ITENS_VENDA(ID, VALOR_UNITARIO, QUANTIDADE, VENDAS_ID, PRODUTOS_ID) VALUES(NULL, 5, 7, 3, 2);
INSERT INTO ITENS_VENDA(ID, VALOR_UNITARIO, QUANTIDADE, VENDAS_ID, PRODUTOS_ID) VALUES(NULL, 20, 13, 4, 3);

DELETE FROM VENDAS WHERE TOTAL > 100;
SELECT * FROM LOJAS WHERE TIPO = 'SUPERMERCADO';
SELECT * FROM VENDAS WHERE TOTAL BETWEEN 50 AND 250;
SELECT * FROM CLIENTES WHERE ESTADO = 'SP';
SELECT COUNT(VALOR) FROM(PRODUTOS) WHERE VALOR > 200;
SELECT DESCRICAO,VALOR FROM PRODUTOS WHERE QUANTIDADE < 20;
SELECT AVG(TOTAL) FROM VENDAS WHERE DATA BETWEEN 2012-01-01 AND 2012-01-02;
SELECT COUNT(*) FROM LOJAS WHERE EMPRESA_ID = 2;
SELECT COUNT(*) FROM VENDAS WHERE HORA BETWEEN '19:00' AND '22:00';
SELECT NOME,ENDERECO FROM CLIENTES WHERE ESTADO = 'SP' OR 'MG' ORDER BY NOME;
SELECT COUNT(*) FROM ITENS_VENDA WHERE QUANTIDADE > 10;
SELECT * FROM ITENS_VENDA WHERE QUANTIDADE BETWEEN 2 AND 5;
SELECT AVG(VALOR_UNITARIO) FROM ITENS_VENDA WHERE QUANTIDADE > 3;
SELECT DESCRICAO,VALOR,QUANTIDADE FROM PRODUTOS WHERE ID BETWEEN 15 AND 30;
DELETE FROM PRODUTOS WHERE VALOR > 100;
