CREATE DATABASE VENDASJOIN;
USE VENDASJOIN;

CREATE TABLE CLIENTES(
	ID		 INT UNSIGNED NOT NULL AUTO_INCREMENT,
	NOME	 VARCHAR(80) NOT NULL,
    ENDERECO VARCHAR(45) NOT NULL,
    CIDADE	 VARCHAR(45) NOT NULL,
    EMAIL	 VARCHAR(100) NOT NULL,
    IDADE	 INT NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE USUARIOS(
	ID		INT UNSIGNED NOT NULL AUTO_INCREMENT,
	NOME	VARCHAR(80) NOT NULL,
	LOGIN	CHAR(15) NOT NULL,
    SENHA	CHAR(6) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE VENDAS(
	ID				INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DATA_ENTREGA	DATE NOT NULL,
    DATA_VENDA		DATE NOT NULL,
    VALOR 			DOUBLE(9,2) NOT NULL,
    CLIENTES_ID		INT UNSIGNED NOT NULL,
    USUARIOS_ID		INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
    FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID),
    FOREIGN KEY(USUARIOS_ID) REFERENCES USUARIOS(ID)
)ENGINE=INNODB;

CREATE TABLE PRODUTOS(
	ID		   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DESCRICAO  VARCHAR(100) NOT NULL,
    VALOR	   DOUBLE(9,2) NOT NULL,
    UNIDADE    VARCHAR(20) NOT NULL,
    QUANTIDADE INT NOT NULL,
	PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE ITENS_VENDAS(
	ID		   	 INT UNSIGNED NOT NULL AUTO_INCREMENT,
    QUANTIDADE 	 INT NOT NULL,
    VALOR_UNIT 	 DOUBLE(9,2) NOT NULL,
	VENDAS_ID	 INT UNSIGNED NOT NULL,
    PRODUTOS_ID	 INT UNSIGNED NOT NULL,
    FOREIGN KEY(VENDAS_ID) REFERENCES VENDAS(ID),
    FOREIGN KEY(PRODUTOS_ID) REFERENCES PRODUTOS(ID),
	PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE BOLETAS(
	ID			INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DESCRICAO	VARCHAR(80) NOT NULL,
    JUROS		DOUBLE(9,2) NOT NULL,
    MULTA		DOUBLE(9,2) NOT NULL,
    VALOR		DOUBLE(9,2) NOT NULL,
    DATA		DATE NOT NULL,
    DATA_VENCI	DATE NOT NULL,
    VENDAS_ID	INT UNSIGNED NOT NULL,
    FOREIGN KEY(VENDAS_ID) REFERENCES VENDAS(ID),
    PRIMARY KEY(ID)
)ENGINE=INNODB;

INSERT INTO CLIENTES(ID, NOME, ENDERECO, CIDADE, EMAIL, IDADE)
VALUES(NULL, "BOB ESPONJA", "RUA DOS MARES", "FENDA DO BIKINI", "BOBESPONJA@BIKINI.COM", 16);

INSERT INTO USUARIOS(ID, NOME, LOGIN, SENHA)
VALUES(NULL, "BOB ESPONJA", "BOB_ESPONJA1234", "ABCDEF");

INSERT INTO VENDAS(ID, DATA_ENTREGA, DATA_VENDA, VALOR, CLIENTES_ID, USUARIOS_ID)
VALUES(NULL, "2020/08/04", "2020/08/03", 200000.00, 1, 1); 

INSERT INTO PRODUTOS(ID, DESCRICAO, VALOR, UNIDADE, QUANTIDADE)
VALUES(NULL, "LEVE UM DELICIOSO HAMBURGUER DE SIRI", 15.99, "SIRI CASCUDO", 125);

INSERT INTO ITENS_VENDAS(ID, QUANTIDADE, VALOR_UNIT, VENDAS_ID, PRODUTOS_ID)
VALUES(NULL, 125, 15.99, 1,1);

INSERT INTO BOLETAS(ID, DESCRICAO, JUROS, MULTA, VALOR, DATA, DATA_VENCI, VENDAS_ID)
VALUES(NULL, "UMA BOLETA!", 1.99, 2.99, 5.99, "2020/08/02", "2020/08/06", 1);
